#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

cd $OPENSHIFT_REPO_DIR

export PATH=$OPENSHIFT_DATA_DIR/node-v0.10.22-linux-x64/bin/:$PATH

nohup node server.js & 
